return {
    ansible = false,
    docker = false,
    flutter = false,
    go = false,
    java = false,
    jinja = false,
    json = false,
    latex = false,
    lua = false,
    markdown = false,
    nvim = false,
    ocaml = false,
    orgmode = false,
    python = false,
    rust = false,
    shell = false,
    toml = false,
    web = false,
    xml = false,
    yaml = false,
}
