return {
    ansible = false,
    clang = false,
    docker = false,
    elixir = false,
    go = false,
    json = false,
    java = false,
    javascript = false,
    lua = false,
    markdown = false,
    nvim = false,
    nginx = false,
    php = false,
    python = false,
    ruby = false,
    rust = false,
    shell = false,
    sql = false,
    terraform = false,
    tex = false,
    -- TODO: remove typescript conf and key, maybe change name to include both
    typescript = false,
    vue = false,
    web = false,
    yaml = false,
    zig = false,
}
